### ISSUE TITLE
Click on application box should open that application

### ISSUE THREAD

**Issue by hvge** [wultra/wultra-developers#13]
Currently, only clicking on "Documentation" link in app's box opens page for that application. I think that we may allow to click also on an upper part of the box to open the documentation.

See picture below - green is current situation, red + green is after the change:
<img width="438" alt="Screen Shot 2019-04-29 at 10 57 28" src="https://user-images.githubusercontent.com/1719814/56885871-e2c43600-6a6d-11e9-8914-0a9f69909034.png">

**Comment by petrdvorak** [comment]
I will fix this one in the redesign by making the title clickable.
